package com.maker.crm.dao.clue;

import com.maker.crm.model.Clue;

import java.util.List;
import java.util.Map;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int updateByPrimaryKey(Clue record);

    int insertClue(Clue clue)throws Exception;

    List<Clue> selectClueSplit(Map<String,Object> map)throws Exception;
    long selectClueCountByCondition(Map<String,Object> map)throws Exception;

    Clue selectClueById(String id)throws Exception;



}