package com.maker.crm.dao.clue;

import com.maker.crm.model.ClueActivityRelation;

import java.util.List;

public interface ClueActivityRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int insert(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int insertSelective(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    ClueActivityRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int updateByPrimaryKeySelective(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Mar 06 17:52:18 CST 2023
     */
    int updateByPrimaryKey(ClueActivityRelation record);

    int insertClueActivityRelationBatch(List<ClueActivityRelation> carList)throws Exception;

    int deleteClueActivityRelationByAidCid(ClueActivityRelation clueActivityRelation)throws Exception;

    List<ClueActivityRelation> selectClueActivityRelationByCid(String cid)throws Exception;

    int deleteClueActivityRelationByCid(String cid)throws Exception;
}