package com.maker.crm.dao.tran;

import com.maker.crm.model.FunnelVo;
import com.maker.crm.model.Transaction;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int insert(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int insertSelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    Transaction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int updateByPrimaryKeySelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int updateByPrimaryKey(Transaction record);

    int insertTransaction(Transaction transaction)throws Exception;

    List<Transaction> selectTransactionSplitByCondition(Map<String,Object> map)throws Exception;

    int selectTransactionCountByCondition(Map<String,Object> map)throws Exception;

    Transaction selectTransactionDetailById(String id)throws Exception;

    int updateTransactionStageByTranId(@Param("tranId") String tranId, @Param("stageId") String stageId)throws Exception;

    List<FunnelVo> selectTransactionFunnelVo()throws Exception;

}