package com.maker.crm.dao.tran;

import com.maker.crm.model.Transaction;
import com.maker.crm.model.TransactionRemark;

import java.util.List;

public interface TransactionRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int insert(TransactionRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int insertSelective(TransactionRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    TransactionRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int updateByPrimaryKeySelective(TransactionRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Tue Mar 28 14:57:36 CST 2023
     */
    int updateByPrimaryKey(TransactionRemark record);

    int insertTransactionRemarkBatch(List<TransactionRemark> transactionRemarkList)throws Exception;

    List<TransactionRemark> selectTransactionRemarkByTranId(String tranId)throws Exception;

}