package com.maker.crm.dao.customer;

import com.maker.crm.model.Customer;

import java.util.List;
import java.util.Map;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Fri Mar 24 15:23:14 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Fri Mar 24 15:23:14 CST 2023
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Fri Mar 24 15:23:14 CST 2023
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Fri Mar 24 15:23:14 CST 2023
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Fri Mar 24 15:23:14 CST 2023
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Fri Mar 24 15:23:14 CST 2023
     */
    int updateByPrimaryKey(Customer record);

    int insertCustomer(Customer customer);

    List<Customer> selectCustomerSplitByCondition(Map<String,Object> map)throws Exception;

    int selectCustomerCount()throws Exception;

    List<Customer> selectAllCustomerByName(String customerName)throws Exception;

    Customer selectOneCustomerByName(String customerName)throws Exception;

}